FROM rabbitmq:3.7-management

WORKDIR /

COPY ./config/rabbitmq.conf /etc/rabbitmq/

RUN chown rabbitmq:rabbitmq /etc/rabbitmq/rabbitmq.conf
RUN rabbitmq-plugins enable rabbitmq_management
EXPOSE 15672
ENTRYPOINT ["rabbitmq-server"]